unified_mode     'true'
name             'keepalived'
maintainer       'David Vanhoucke'
maintainer_email 'dvanhoucke@redborder.com'
license          'All rights reserved'
description      'Installs/Configures cookbook-keepalived'
version          '0.3.1'
